### ISSUE TITLE
Can only update 1 attribute

### ISSUE THREAD

**Issue by erikvanoosten** [sparsetech/pine#42]
The following code compiles but fails at run time:

```scala
val tableTemplate = html"""<table><tr id="row"></tr></table>"""
val rowTemplate = tableTemplate.byId("row").as[tag.Tr]
val row = TagRef[tag.Tr]("row")
rowTemplate.update { implicit ctx =>
  row.id := "test1"        // choose one,
  row.`class` := "test"    // not both
}
```

with:

```
java.lang.Exception: Some diffs could not be applied: Queue((ById(row),SetAttribute(Attribute(ById(row),class),test)))
	at pine.NodeRenderContext.commit(RenderContext.scala:45)
	at pine.Tag.update(Node.scala:114)
```

When you comment out one of the 2 `:=` instructions, everything works as expected.

**Comment by tindzk** [comment]
The problem is that you first update the ID of the node, whereby the second tag reference cannot be resolved. If you change the order by setting the ID last, it should work as expected.

**Comment by erikvanoosten** [comment]
Thanks!
